version: '3.9'

services:
  juggler-frontend:
    labels:
      - traefik.enable=true
      - traefik.http.routers.juggler-frontend.rule=Host(`${JUGGLER_FRONTEND_UI_URL}`) 
      - traefik.http.routers.juggler-frontend.entrypoints=https
      - traefik.http.services.juggler-frontend.loadbalancer.server.port=80

networks:
  default:
    external: true
    name: blowfish-network
